builders:
  envify:
    import: "package:envify_generator/builder.dart"
    builder_factories: ["envifyBuilder"]
    build_extensions: {".dart": [".envify.g.part"]}
    build_to: cache
    auto_apply: dependents
    applies_builders: ["source_gen|combining_builder"]
