name: example
version: 0.0.1
description: An example for envify.

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  envify:
    git:
      url: https://github.com/techouse/envify.git
      ref: main
      path: envify
dev_dependencies:
  build_runner: ^2.0.0
  envify_generator:

dependency_overrides:
  envify_generator:
    path: ../../envify_generator
